server:
  port: 8083

spring:
  mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE:trading}
  application:
    name: price-service
  profiles:
    active: user
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    stomp:
      port: ${SPRING_RABBITMQ_STOMP_PORT:61613}



eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

price:
  symbols: ${PRICE_SYMBOLS}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


