spring:
  application:
    name: user-service
  mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE:trading}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour in milliseconds

management:
  health:
    mongodb:
      enabled: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

token:
  secret: ${JWT_SECRET}
